### ISSUE TITLE
Failing spec:  ./spec/controllers/admin/category_controller_spec.rb

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#964]
````
Failures:

  1) Admin::CategoriesController translations show the correct translation when 'I18n.locale :en'
     Failure/Error: expect(assigns(:category).name).to eq 'Science'

       expected: "Science"
            got: "Wissenschaft"

       (compared using ==)
     # ./spec/controllers/admin/category_controller_spec.rb:125:in `block (3 levels) in <main>'
````
Assumption: there are 2 translations for `locale: 'en'` and there could be a problem retrieving the right one. Why is it possible to create an extra translation for this locale? 

#<ActiveRecord::Associations::CollectionProxy [#<Category::Translation id: 3, category_id: 1, locale: "en", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: nil>, #<Category::Translation id: 2, category_id: 1, locale: "de", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: "Wissenschaft">, #<Category::Translation id: 1, category_id: 1, locale: "en", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: "Science">]
